/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabajadorLoginRouteImport } from './routes/trabajador-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCodeRouteImport } from './routes/auth/code'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedTransferirRouteImport } from './routes/_authenticated/transferir'
import { Route as AuthenticatedTrabajadorPanelRouteImport } from './routes/_authenticated/trabajador-panel'
import { Route as AuthenticatedTarjetasRouteImport } from './routes/_authenticated/tarjetas'
import { Route as AuthenticatedRetirarRouteImport } from './routes/_authenticated/retirar'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMembresiasRouteImport } from './routes/_authenticated/membresias'
import { Route as AuthenticatedMdtRouteImport } from './routes/_authenticated/mdt'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedEstadoCuentaRouteImport } from './routes/_authenticated/estado-cuenta'
import { Route as AuthenticatedDepositarRouteImport } from './routes/_authenticated/depositar'
import { Route as AuthenticatedCreditoRouteImport } from './routes/_authenticated/credito'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthSecretClaveSecretaRouteImport } from './routes/auth/secret/clave-secreta'
import { Route as ApiPublicObtenerClaveServicioRouteImport } from './routes/api/public/obtener-clave-servicio'
import { Route as ApiPublicDeshabilitarClaveServicioRouteImport } from './routes/api/public/deshabilitar-clave-servicio'
import { Route as ApiPublicCronImpuestosRouteImport } from './routes/api/public/cron-impuestos'
import { Route as ApiPublicCronCreditRemindersRouteImport } from './routes/api/public/cron-credit-reminders'

const TrabajadorLoginRoute = TrabajadorLoginRouteImport.update({
  id: '/trabajador-login',
  path: '/trabajador-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCodeRoute = AuthCodeRouteImport.update({
  id: '/auth/code',
  path: '/auth/code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransferirRoute = AuthenticatedTransferirRouteImport.update({
  id: '/transferir',
  path: '/transferir',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrabajadorPanelRoute =
  AuthenticatedTrabajadorPanelRouteImport.update({
    id: '/trabajador-panel',
    path: '/trabajador-panel',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTarjetasRoute = AuthenticatedTarjetasRouteImport.update({
  id: '/tarjetas',
  path: '/tarjetas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRetirarRoute = AuthenticatedRetirarRouteImport.update({
  id: '/retirar',
  path: '/retirar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembresiasRoute = AuthenticatedMembresiasRouteImport.update({
  id: '/membresias',
  path: '/membresias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMdtRoute = AuthenticatedMdtRouteImport.update({
  id: '/mdt',
  path: '/mdt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstadoCuentaRoute =
  AuthenticatedEstadoCuentaRouteImport.update({
    id: '/estado-cuenta',
    path: '/estado-cuenta',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepositarRoute = AuthenticatedDepositarRouteImport.update({
  id: '/depositar',
  path: '/depositar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreditoRoute = AuthenticatedCreditoRouteImport.update({
  id: '/credito',
  path: '/credito',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSecretClaveSecretaRoute = AuthSecretClaveSecretaRouteImport.update({
  id: '/auth/secret/clave-secreta',
  path: '/auth/secret/clave-secreta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicObtenerClaveServicioRoute =
  ApiPublicObtenerClaveServicioRouteImport.update({
    id: '/api/public/obtener-clave-servicio',
    path: '/api/public/obtener-clave-servicio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeshabilitarClaveServicioRoute =
  ApiPublicDeshabilitarClaveServicioRouteImport.update({
    id: '/api/public/deshabilitar-clave-servicio',
    path: '/api/public/deshabilitar-clave-servicio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronImpuestosRoute = ApiPublicCronImpuestosRouteImport.update({
  id: '/api/public/cron-impuestos',
  path: '/api/public/cron-impuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCreditRemindersRoute =
  ApiPublicCronCreditRemindersRouteImport.update({
    id: '/api/public/cron-credit-reminders',
    path: '/api/public/cron-credit-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/trabajador-login': typeof TrabajadorLoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/credito': typeof AuthenticatedCreditoRoute
  '/depositar': typeof AuthenticatedDepositarRoute
  '/estado-cuenta': typeof AuthenticatedEstadoCuentaRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mdt': typeof AuthenticatedMdtRoute
  '/membresias': typeof AuthenticatedMembresiasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/retirar': typeof AuthenticatedRetirarRoute
  '/tarjetas': typeof AuthenticatedTarjetasRoute
  '/trabajador-panel': typeof AuthenticatedTrabajadorPanelRoute
  '/transferir': typeof AuthenticatedTransferirRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/code': typeof AuthCodeRoute
  '/api/public/cron-credit-reminders': typeof ApiPublicCronCreditRemindersRoute
  '/api/public/cron-impuestos': typeof ApiPublicCronImpuestosRoute
  '/api/public/deshabilitar-clave-servicio': typeof ApiPublicDeshabilitarClaveServicioRoute
  '/api/public/obtener-clave-servicio': typeof ApiPublicObtenerClaveServicioRoute
  '/auth/secret/clave-secreta': typeof AuthSecretClaveSecretaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/trabajador-login': typeof TrabajadorLoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/credito': typeof AuthenticatedCreditoRoute
  '/depositar': typeof AuthenticatedDepositarRoute
  '/estado-cuenta': typeof AuthenticatedEstadoCuentaRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mdt': typeof AuthenticatedMdtRoute
  '/membresias': typeof AuthenticatedMembresiasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/retirar': typeof AuthenticatedRetirarRoute
  '/tarjetas': typeof AuthenticatedTarjetasRoute
  '/trabajador-panel': typeof AuthenticatedTrabajadorPanelRoute
  '/transferir': typeof AuthenticatedTransferirRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/code': typeof AuthCodeRoute
  '/api/public/cron-credit-reminders': typeof ApiPublicCronCreditRemindersRoute
  '/api/public/cron-impuestos': typeof ApiPublicCronImpuestosRoute
  '/api/public/deshabilitar-clave-servicio': typeof ApiPublicDeshabilitarClaveServicioRoute
  '/api/public/obtener-clave-servicio': typeof ApiPublicObtenerClaveServicioRoute
  '/auth/secret/clave-secreta': typeof AuthSecretClaveSecretaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/trabajador-login': typeof TrabajadorLoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/credito': typeof AuthenticatedCreditoRoute
  '/_authenticated/depositar': typeof AuthenticatedDepositarRoute
  '/_authenticated/estado-cuenta': typeof AuthenticatedEstadoCuentaRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/mdt': typeof AuthenticatedMdtRoute
  '/_authenticated/membresias': typeof AuthenticatedMembresiasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/retirar': typeof AuthenticatedRetirarRoute
  '/_authenticated/tarjetas': typeof AuthenticatedTarjetasRoute
  '/_authenticated/trabajador-panel': typeof AuthenticatedTrabajadorPanelRoute
  '/_authenticated/transferir': typeof AuthenticatedTransferirRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/code': typeof AuthCodeRoute
  '/api/public/cron-credit-reminders': typeof ApiPublicCronCreditRemindersRoute
  '/api/public/cron-impuestos': typeof ApiPublicCronImpuestosRoute
  '/api/public/deshabilitar-clave-servicio': typeof ApiPublicDeshabilitarClaveServicioRoute
  '/api/public/obtener-clave-servicio': typeof ApiPublicObtenerClaveServicioRoute
  '/auth/secret/clave-secreta': typeof AuthSecretClaveSecretaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/login'
    | '/trabajador-login'
    | '/admin'
    | '/credito'
    | '/depositar'
    | '/estado-cuenta'
    | '/historial'
    | '/home'
    | '/mdt'
    | '/membresias'
    | '/perfil'
    | '/retirar'
    | '/tarjetas'
    | '/trabajador-panel'
    | '/transferir'
    | '/auth/callback'
    | '/auth/code'
    | '/api/public/cron-credit-reminders'
    | '/api/public/cron-impuestos'
    | '/api/public/deshabilitar-clave-servicio'
    | '/api/public/obtener-clave-servicio'
    | '/auth/secret/clave-secreta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/login'
    | '/trabajador-login'
    | '/admin'
    | '/credito'
    | '/depositar'
    | '/estado-cuenta'
    | '/historial'
    | '/home'
    | '/mdt'
    | '/membresias'
    | '/perfil'
    | '/retirar'
    | '/tarjetas'
    | '/trabajador-panel'
    | '/transferir'
    | '/auth/callback'
    | '/auth/code'
    | '/api/public/cron-credit-reminders'
    | '/api/public/cron-impuestos'
    | '/api/public/deshabilitar-clave-servicio'
    | '/api/public/obtener-clave-servicio'
    | '/auth/secret/clave-secreta'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/login'
    | '/trabajador-login'
    | '/_authenticated/admin'
    | '/_authenticated/credito'
    | '/_authenticated/depositar'
    | '/_authenticated/estado-cuenta'
    | '/_authenticated/historial'
    | '/_authenticated/home'
    | '/_authenticated/mdt'
    | '/_authenticated/membresias'
    | '/_authenticated/perfil'
    | '/_authenticated/retirar'
    | '/_authenticated/tarjetas'
    | '/_authenticated/trabajador-panel'
    | '/_authenticated/transferir'
    | '/auth/callback'
    | '/auth/code'
    | '/api/public/cron-credit-reminders'
    | '/api/public/cron-impuestos'
    | '/api/public/deshabilitar-clave-servicio'
    | '/api/public/obtener-clave-servicio'
    | '/auth/secret/clave-secreta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  LoginRoute: typeof LoginRoute
  TrabajadorLoginRoute: typeof TrabajadorLoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCodeRoute: typeof AuthCodeRoute
  ApiPublicCronCreditRemindersRoute: typeof ApiPublicCronCreditRemindersRoute
  ApiPublicCronImpuestosRoute: typeof ApiPublicCronImpuestosRoute
  ApiPublicDeshabilitarClaveServicioRoute: typeof ApiPublicDeshabilitarClaveServicioRoute
  ApiPublicObtenerClaveServicioRoute: typeof ApiPublicObtenerClaveServicioRoute
  AuthSecretClaveSecretaRoute: typeof AuthSecretClaveSecretaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabajador-login': {
      id: '/trabajador-login'
      path: '/trabajador-login'
      fullPath: '/trabajador-login'
      preLoaderRoute: typeof TrabajadorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/code': {
      id: '/auth/code'
      path: '/auth/code'
      fullPath: '/auth/code'
      preLoaderRoute: typeof AuthCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transferir': {
      id: '/_authenticated/transferir'
      path: '/transferir'
      fullPath: '/transferir'
      preLoaderRoute: typeof AuthenticatedTransferirRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trabajador-panel': {
      id: '/_authenticated/trabajador-panel'
      path: '/trabajador-panel'
      fullPath: '/trabajador-panel'
      preLoaderRoute: typeof AuthenticatedTrabajadorPanelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarjetas': {
      id: '/_authenticated/tarjetas'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof AuthenticatedTarjetasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/retirar': {
      id: '/_authenticated/retirar'
      path: '/retirar'
      fullPath: '/retirar'
      preLoaderRoute: typeof AuthenticatedRetirarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membresias': {
      id: '/_authenticated/membresias'
      path: '/membresias'
      fullPath: '/membresias'
      preLoaderRoute: typeof AuthenticatedMembresiasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mdt': {
      id: '/_authenticated/mdt'
      path: '/mdt'
      fullPath: '/mdt'
      preLoaderRoute: typeof AuthenticatedMdtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estado-cuenta': {
      id: '/_authenticated/estado-cuenta'
      path: '/estado-cuenta'
      fullPath: '/estado-cuenta'
      preLoaderRoute: typeof AuthenticatedEstadoCuentaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/depositar': {
      id: '/_authenticated/depositar'
      path: '/depositar'
      fullPath: '/depositar'
      preLoaderRoute: typeof AuthenticatedDepositarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credito': {
      id: '/_authenticated/credito'
      path: '/credito'
      fullPath: '/credito'
      preLoaderRoute: typeof AuthenticatedCreditoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/secret/clave-secreta': {
      id: '/auth/secret/clave-secreta'
      path: '/auth/secret/clave-secreta'
      fullPath: '/auth/secret/clave-secreta'
      preLoaderRoute: typeof AuthSecretClaveSecretaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/obtener-clave-servicio': {
      id: '/api/public/obtener-clave-servicio'
      path: '/api/public/obtener-clave-servicio'
      fullPath: '/api/public/obtener-clave-servicio'
      preLoaderRoute: typeof ApiPublicObtenerClaveServicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deshabilitar-clave-servicio': {
      id: '/api/public/deshabilitar-clave-servicio'
      path: '/api/public/deshabilitar-clave-servicio'
      fullPath: '/api/public/deshabilitar-clave-servicio'
      preLoaderRoute: typeof ApiPublicDeshabilitarClaveServicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-impuestos': {
      id: '/api/public/cron-impuestos'
      path: '/api/public/cron-impuestos'
      fullPath: '/api/public/cron-impuestos'
      preLoaderRoute: typeof ApiPublicCronImpuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-credit-reminders': {
      id: '/api/public/cron-credit-reminders'
      path: '/api/public/cron-credit-reminders'
      fullPath: '/api/public/cron-credit-reminders'
      preLoaderRoute: typeof ApiPublicCronCreditRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreditoRoute: typeof AuthenticatedCreditoRoute
  AuthenticatedDepositarRoute: typeof AuthenticatedDepositarRoute
  AuthenticatedEstadoCuentaRoute: typeof AuthenticatedEstadoCuentaRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMdtRoute: typeof AuthenticatedMdtRoute
  AuthenticatedMembresiasRoute: typeof AuthenticatedMembresiasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRetirarRoute: typeof AuthenticatedRetirarRoute
  AuthenticatedTarjetasRoute: typeof AuthenticatedTarjetasRoute
  AuthenticatedTrabajadorPanelRoute: typeof AuthenticatedTrabajadorPanelRoute
  AuthenticatedTransferirRoute: typeof AuthenticatedTransferirRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreditoRoute: AuthenticatedCreditoRoute,
  AuthenticatedDepositarRoute: AuthenticatedDepositarRoute,
  AuthenticatedEstadoCuentaRoute: AuthenticatedEstadoCuentaRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMdtRoute: AuthenticatedMdtRoute,
  AuthenticatedMembresiasRoute: AuthenticatedMembresiasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRetirarRoute: AuthenticatedRetirarRoute,
  AuthenticatedTarjetasRoute: AuthenticatedTarjetasRoute,
  AuthenticatedTrabajadorPanelRoute: AuthenticatedTrabajadorPanelRoute,
  AuthenticatedTransferirRoute: AuthenticatedTransferirRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  LoginRoute: LoginRoute,
  TrabajadorLoginRoute: TrabajadorLoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCodeRoute: AuthCodeRoute,
  ApiPublicCronCreditRemindersRoute: ApiPublicCronCreditRemindersRoute,
  ApiPublicCronImpuestosRoute: ApiPublicCronImpuestosRoute,
  ApiPublicDeshabilitarClaveServicioRoute:
    ApiPublicDeshabilitarClaveServicioRoute,
  ApiPublicObtenerClaveServicioRoute: ApiPublicObtenerClaveServicioRoute,
  AuthSecretClaveSecretaRoute: AuthSecretClaveSecretaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
